### **Importing libraries**

In [20]:
import numpy as np
import pandas as pd
import GEOparse

from scipy.stats import ttest_ind
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from statsmodels.stats.multitest import multipletests
from sklearn.feature_selection import SelectKBest, f_classif

### **Load dataset from GEO.soft file**
Replace the path with your actual file location

In [ ]:
gse = GEOparse.get_GEO(filepath=r"C:\Users\Asrefanavary\Desktop\GSE18123_family.soft")

23-Jul-2026 16:57:46 INFO GEOparse - Parsing C:\Users\Asrefanavary\Desktop\GSE18123_family.soft:
23-Jul-2026 16:57:46 DEBUG GEOparse - DATABASE: GeoMiame
23-Jul-2026 16:57:46 DEBUG GEOparse - SERIES: GSE18123
23-Jul-2026 16:57:46 DEBUG GEOparse - PLATFORM: GPL570
c:\Users\Asrefanavary\anaconda3\Lib\site-packages\GEOparse\GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
23-Jul-2026 16:57:49 DEBUG GEOparse - PLATFORM: GPL6244
23-Jul-2026 16:57:53 DEBUG GEOparse - SAMPLE: GSM650510
23-Jul-2026 16:57:53 DEBUG GEOparse - SAMPLE: GSM650512
23-Jul-2026 16:57:53 DEBUG GEOparse - SAMPLE: GSM650513
23-Jul-2026 16:57:54 DEBUG GEOparse - SAMPLE: GSM650514
23-Jul-2026 16:57:54 DEBUG GEOparse - SAMPLE: GSM650515
23-Jul-2026 16:57:54 DEBUG GEOparse - SAMPLE: GSM650516
23-Jul-2026 16:57:54 DEBUG GEOparse - SAMPLE: GSM650517
23-Jul-2026 16:57:54 DEBUG GEOparse - SAMPLE: GSM650518
23-Jul-2026 16:57:54 DEBUG GEOparse - SAMPLE: GSM650519
23-Jul-2026 16:57:55 DEBUG GEOparse - SAMPLE: GSM650520
23-Jul-2026 16:57:55 DEBUG GEOparse - SAMPLE: GSM650521
23-Jul-2026 16:57:55 DEBUG GEOparse - SAMPLE: GSM650522
23-Jul-2026 16:57:55 DEBUG GEOparse - SAMPLE: GSM650523
23-Jul-2026 16:57:55 DEBUG GEOparse - SAMPLE: GSM650525
23-Jul-2026 16:57:55 DEBUG GEOparse - SAMPLE: GSM650526
23-Jul-2026 16:57:56 DEBUG GEOparse - SAMPLE: GSM650527
23-Jul-2026 16:57:56 DEBUG GEOparse - SAMPLE: GSM650528
23-Jul-2026 16:57:56 DEBUG GEOparse - SAMPLE: GSM650529
23-Jul-2026 16:57:56 DEBUG GEOparse - SAMPLE: GSM650530
23-Jul-2026 16:57:56 DEBUG GEOparse - SAMPLE: GSM650531
23-Jul-2026 16:57:56 DEBUG GEOparse - SAMPLE: GSM650532
23-Jul-2026 16:57:57 DEBUG GEOparse - SAMPLE: GSM650533
23-Jul-2026 16:57:57 DEBUG GEOparse - SAMPLE: GSM650534
23-Jul-2026 16:57:57 DEBUG GEOparse - SAMPLE: GSM650536
23-Jul-2026 16:57:57 DEBUG GEOparse - SAMPLE: GSM650537
23-Jul-2026 16:57:57 DEBUG GEOparse - SAMPLE: GSM650538
23-Jul-2026 16:57:58 DEBUG GEOparse - SAMPLE: GSM650540
23-Jul-2026 16:57:58 DEBUG GEOparse - SAMPLE: GSM650541
23-Jul-2026 16:57:58 DEBUG GEOparse - SAMPLE: GSM650542
23-Jul-2026 16:57:58 DEBUG GEOparse - SAMPLE: GSM650543
23-Jul-2026 16:57:58 DEBUG GEOparse - SAMPLE: GSM650544
23-Jul-2026 16:57:58 DEBUG GEOparse - SAMPLE: GSM650545
23-Jul-2026 16:57:59 DEBUG GEOparse - SAMPLE: GSM650546
23-Jul-2026 16:57:59 DEBUG GEOparse - SAMPLE: GSM650547
23-Jul-2026 16:57:59 DEBUG GEOparse - SAMPLE: GSM650548
23-Jul-2026 16:57:59 DEBUG GEOparse - SAMPLE: GSM650549
23-Jul-2026 16:57:59 DEBUG GEOparse - SAMPLE: GSM650550
23-Jul-2026 16:57:59 DEBUG GEOparse - SAMPLE: GSM650551
23-Jul-2026 16:58:00 DEBUG GEOparse - SAMPLE: GSM650552
23-Jul-2026 16:58:00 DEBUG GEOparse - SAMPLE: GSM650553
23-Jul-2026 16:58:00 DEBUG GEOparse - SAMPLE: GSM650554
23-Jul-2026 16:58:00 DEBUG GEOparse - SAMPLE: GSM650555
23-Jul-2026 16:58:00 DEBUG GEOparse - SAMPLE: GSM650556
23-Jul-2026 16:58:00 DEBUG GEOparse - SAMPLE: GSM650557
23-Jul-2026 16:58:01 DEBUG GEOparse - SAMPLE: GSM650558
23-Jul-2026 16:58:01 DEBUG GEOparse - SAMPLE: GSM650560
23-Jul-2026 16:58:01 DEBUG GEOparse - SAMPLE: GSM650561
23-Jul-2026 16:58:01 DEBUG GEOparse - SAMPLE: GSM650562
23-Jul-2026 16:58:01 DEBUG GEOparse - SAMPLE: GSM650563
23-Jul-2026 16:58:01 DEBUG GEOparse - SAMPLE: GSM650564
23-Jul-2026 16:58:02 DEBUG GEOparse - SAMPLE: GSM650565
23-Jul-2026 16:58:02 DEBUG GEOparse - SAMPLE: GSM650566
23-Jul-2026 16:58:02 DEBUG GEOparse - SAMPLE: GSM650567
23-Jul-2026 16:58:02 DEBUG GEOparse - SAMPLE: GSM650568
23-Jul-2026 16:58:02 DEBUG GEOparse - SAMPLE: GSM650569
23-Jul-2026 16:58:02 DEBUG GEOparse - SAMPLE: GSM650570
23-Jul-2026 16:58:03 DEBUG GEOparse - SAMPLE: GSM650571
23-Jul-2026 16:58:03 DEBUG GEOparse - SAMPLE: GSM650572
23-Jul-2026 16:58:03 DEBUG GEOparse - SAMPLE: GSM650573
23-Jul-2026 16:58:03 DEBUG GEOparse - SAMPLE: GSM650574
23-Jul-2026 16:58:03 DEBUG GEOparse - SAMPLE: GSM650575
23-Jul-2026 16:58:03 DEBUG GEOparse - SAMPLE: GSM650577
23-Jul-2026 16:58:04 DEBUG GEOparse - SAMPLE: GSM650578
23-Jul-2026 16:58:04 DEBUG GEOparse - SAMPLE: GSM650579
23-Jul-2026 16:58:04 DEBUG GEOparse - SAMPLE: GSM650580
23-Jul-2026 16:58:04 DEBUG GEOparse - SAMPLE: GSM650581
23-Jul-2026 16:58:04 DEBUG GEOparse - SAMPLE: GSM650600
23-Jul-2026 16:58:05 DEBUG GEOparse - SAMPLE: GSM650603
23-Jul-2026 16:58:05 DEBUG GEOparse - SAMPLE: GSM650604
23-Jul-2026 16:58:05 DEBUG GEOparse - SAMPLE: GSM650606
23-Jul-2026 16:58:05 DEBUG GEOparse - SAMPLE: GSM650607
23-Jul-2026 16:58:05 DEBUG GEOparse - SAMPLE: GSM650614
23-Jul-2026 16:58:05 DEBUG GEOparse - SAMPLE: GSM650615
23-Jul-2026 16:58:06 DEBUG GEOparse - SAMPLE: GSM650617
23-Jul-2026 16:58:06 DEBUG GEOparse - SAMPLE: GSM650618
23-Jul-2026 16:58:06 DEBUG GEOparse - SAMPLE: GSM650619
23-Jul-2026 16:58:06 DEBUG GEOparse - SAMPLE: GSM650620
23-Jul-2026 16:58:06 DEBUG GEOparse - SAMPLE: GSM650621
23-Jul-2026 16:58:06 DEBUG GEOparse - SAMPLE: GSM650622
23-Jul-2026 16:58:07 DEBUG GEOparse - SAMPLE: GSM650632
23-Jul-2026 16:58:07 DEBUG GEOparse - SAMPLE: GSM650633
23-Jul-2026 16:58:07 DEBUG GEOparse - SAMPLE: GSM650636
23-Jul-2026 16:58:07 DEBUG GEOparse - SAMPLE: GSM650637
23-Jul-2026 16:58:07 DEBUG GEOparse - SAMPLE: GSM650638
23-Jul-2026 16:58:07 DEBUG GEOparse - SAMPLE: GSM650639
23-Jul-2026 16:58:08 DEBUG GEOparse - SAMPLE: GSM650640
23-Jul-2026 16:58:08 DEBUG GEOparse - SAMPLE: GSM650641
23-Jul-2026 16:58:08 DEBUG GEOparse - SAMPLE: GSM650642
23-Jul-2026 16:58:08 DEBUG GEOparse - SAMPLE: GSM650643
23-Jul-2026 16:58:08 DEBUG GEOparse - SAMPLE: GSM650644
23-Jul-2026 16:58:08 DEBUG GEOparse - SAMPLE: GSM650645
23-Jul-2026 16:58:09 DEBUG GEOparse - SAMPLE: GSM650646
23-Jul-2026 16:58:09 DEBUG GEOparse - SAMPLE: GSM650647
23-Jul-2026 16:58:09 DEBUG GEOparse - SAMPLE: GSM650648
23-Jul-2026 16:58:09 DEBUG GEOparse - SAMPLE: GSM650649
23-Jul-2026 16:58:09 DEBUG GEOparse - SAMPLE: GSM650651
23-Jul-2026 16:58:09 DEBUG GEOparse - SAMPLE: GSM650652
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650653
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650654
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650655
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650656
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650657
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650658
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650659
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650660
23-Jul-2026 16:58:10 DEBUG GEOparse - SAMPLE: GSM650661
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650662
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650663
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650664
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650665
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650666
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650667
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650668
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650669
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650670
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650671
23-Jul-2026 16:58:11 DEBUG GEOparse - SAMPLE: GSM650672
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650673
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650674
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650675
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650676
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650677
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650678
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650679
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650680
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650681
23-Jul-2026 16:58:12 DEBUG GEOparse - SAMPLE: GSM650682
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650683
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650684
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650685
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650686
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650687
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650688
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650689
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650690
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650691
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650692
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650693
23-Jul-2026 16:58:13 DEBUG GEOparse - SAMPLE: GSM650694
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650695
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650696
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650697
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650698
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650699
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650700
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650701
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650702
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650703
23-Jul-2026 16:58:14 DEBUG GEOparse - SAMPLE: GSM650704
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650705
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650706
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650707
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650708
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650709
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650712
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650713
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650714
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650715
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650716
23-Jul-2026 16:58:15 DEBUG GEOparse - SAMPLE: GSM650717
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650718
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650719
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650720
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650721
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650722
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650723
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650724
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650725
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650726
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650727
23-Jul-2026 16:58:16 DEBUG GEOparse - SAMPLE: GSM650728
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650729
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650730
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650731
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650732
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650733
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650734
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650735
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650737
23-Jul-2026 16:58:17 DEBUG GEOparse - SAMPLE: GSM650740
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650744
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650748
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650750
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650752
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650753
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650758
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650760
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650761
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650762
23-Jul-2026 16:58:18 DEBUG GEOparse - SAMPLE: GSM650763
23-Jul-2026 16:58:19 DEBUG GEOparse - SAMPLE: GSM650764
23-Jul-2026 16:58:19 DEBUG GEOparse - SAMPLE: GSM650765
23-Jul-2026 16:58:19 DEBUG GEOparse - SAMPLE: GSM650766
23-Jul-2026 16:58:19 DEBUG GEOparse - SAMPLE: GSM650767
23-Jul-2026 16:58:19 DEBUG GEOparse - SAMPLE: GSM650768
23-Jul-2026 16:58:19 DEBUG GEOparse - SAMPLE: GSM650769
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650770
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650771
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650772
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650773
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650801
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650802
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650806
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650808
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650809
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650813
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650816
23-Jul-2026 16:58:20 DEBUG GEOparse - SAMPLE: GSM650818
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650819
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650820
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650821
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650822
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650823
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650824
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650825
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650826
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650827
23-Jul-2026 16:58:21 DEBUG GEOparse - SAMPLE: GSM650828
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650829
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650830
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650831
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650832
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650833
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650834
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650835
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650836
23-Jul-2026 16:58:22 DEBUG GEOparse - SAMPLE: GSM650837
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650838
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650839
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650840
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650841
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650842
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650843
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650844
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650845
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650846
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650847
23-Jul-2026 16:58:23 DEBUG GEOparse - SAMPLE: GSM650848
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650849
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650850
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650851
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650852
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650853
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650854
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650855
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650856
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650857
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650858
23-Jul-2026 16:58:24 DEBUG GEOparse - SAMPLE: GSM650859
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650860
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650861
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650863
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650864
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650865
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650866
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650867
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650868
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650869
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650870
23-Jul-2026 16:58:25 DEBUG GEOparse - SAMPLE: GSM650871
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650872
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650873
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650874
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650875
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650876
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650877
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650878
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650879
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650880
23-Jul-2026 16:58:26 DEBUG GEOparse - SAMPLE: GSM650883
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650885
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650923
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650924
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650930
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650931
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650944
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650946
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650950
23-Jul-2026 16:58:27 DEBUG GEOparse - SAMPLE: GSM650951
23-Jul-2026 16:58:28 DEBUG GEOparse - SAMPLE: GSM650954
23-Jul-2026 16:58:28 DEBUG GEOparse - SAMPLE: GSM650959
23-Jul-2026 16:58:28 DEBUG GEOparse - SAMPLE: GSM650968
23-Jul-2026 16:58:28 DEBUG GEOparse - SAMPLE: GSM650969
23-Jul-2026 16:58:28 DEBUG GEOparse - SAMPLE: GSM650970
23-Jul-2026 16:58:28 DEBUG GEOparse - SAMPLE: GSM650975


### **Inspecting the GEO Sample**

The first GEO sample (GSM) is extracted from the downloaded dataset, and its expression matrix is examined. The dataset contains 54,613 probes, with each row representing a probe identifier (ID_REF) and its corresponding normalized expression value (VALUE).

In [22]:
gsm = list(gse.gsms.values())[0]

print(gsm.table.shape)
gsm.table.head()

(54613, 2)

      ID_REF      VALUE
0  1007_s_at   26.65640
1    1053_at   39.00726
2     117_at  296.01724
3     121_at  209.03575
4  1255_g_at   63.82730

### **Extracting Sample Metadata**

The metadata of each GEO sample (GSM) are extracted to build a structured sample information table. For every sample, the diagnosis, gender, age at blood collection, and microarray platform are retrieved from the available metadata and stored in a pandas DataFrame.

The resulting table contains **285 samples** and **5 metadata fields** (`Sample`, `Diagnosis`, `Gender`, `Age`, and `Platform`), providing the clinical and demographic information required for subsequent data preprocessing and analysis.

In [23]:
samples_info = []

for gsm_id, gsm in gse.gsms.items():

    diagnosis = None
    gender = None
    age = None

    for item in gsm.metadata.get("characteristics_ch1", []):

        if item.startswith("diagnosis:"):
            diagnosis = item.replace("diagnosis:", "").strip()

        elif item.startswith("gender:"):
            gender = item.replace("gender:", "").strip()

        elif item.startswith("age at blood drawing"):
            age = int(item.split(":")[-1].strip())

    samples_info.append({
        "Sample": gsm_id,
        "Diagnosis": diagnosis,
        "Gender": gender,
        "Age": age,
        "Platform": gsm.metadata["platform_id"][0]
    })

df_samples = pd.DataFrame(samples_info)

In [24]:
df_samples

        Sample Diagnosis Gender  Age Platform
0    GSM650510   PDD-NOS   male  118   GPL570
1    GSM650512   PDD-NOS   male   79   GPL570
2    GSM650513    AUTISM   male  169   GPL570
3    GSM650514    AUTISM   male   92   GPL570
4    GSM650515    AUTISM   male   78   GPL570
..         ...       ...    ...  ...      ...
280  GSM650959   CONTROL   male   28  GPL6244
281  GSM650968   CONTROL   male   51  GPL6244
282  GSM650969   CONTROL   male   37  GPL6244
283  GSM650970   CONTROL   male   49  GPL6244
284  GSM650975   CONTROL   male   48  GPL6244

[285 rows x 5 columns]

### **Selecting the GPL6244 Platform**

The dataset contains samples generated using two different microarray platforms: **GPL570 (99 samples)** and **GPL6244 (186 samples)**. 
Since **GPL6244** includes a substantially larger number of samples, it was selected for the subsequent analyses. Using the platform with the larger sample size provides greater statistical power and ensures a more comprehensive analysis while avoiding potential technical variability introduced by combining data from different platforms.

In [56]:
df_samples["Platform"].unique()

array(['GPL570', 'GPL6244'], dtype=object)

In [57]:
df_samples["Platform"].value_counts()

Platform
GPL6244    186
GPL570      99
Name: count, dtype: int64

In [58]:
df_gpl6244 = df_samples[df_samples["Platform"] == "GPL6244"].copy()

df_gpl6244.shape

(186, 5)

In [26]:
df_gpl6244.head(10)

        Sample            Diagnosis Gender  Age Platform
99   GSM650655  ASPERGER'S DISORDER   male  156  GPL6244
100  GSM650656               AUTISM   male  168  GPL6244
101  GSM650657              CONTROL   male  228  GPL6244
102  GSM650658               AUTISM   male   60  GPL6244
103  GSM650659               AUTISM   male   36  GPL6244
104  GSM650660              PDD-NOS   male   72  GPL6244
105  GSM650661              PDD-NOS   male  108  GPL6244
106  GSM650662  ASPERGER'S DISORDER   male  120  GPL6244
107  GSM650663              PDD-NOS   male   48  GPL6244
108  GSM650664              PDD-NOS   male  108  GPL6244

### **Diagnostic Grouping Strategy**

The original dataset contained four diagnostic categories: **CONTROL**, **PDD-NOS**, **AUTISM**, and **ASPERGER'S DISORDER**. According to the **DSM-IV** criteria, Autism, Asperger's Disorder, and PDD-NOS were classified as pervasive developmental disorders and represent related neurodevelopmental conditions within the autism spectrum.

In the updated **DSM-5** framework, these previously separate diagnoses were integrated into a single clinical category known as **Autism Spectrum Disorder (ASD)**.

The original dataset contained four diagnostic categories:

| Diagnosis | Number of Samples |
|------------|------------------|
| CONTROL | 82 |
| PDD-NOS | 48 |
| AUTISM | 41 |
| ASPERGER'S DISORDER | 15 |

Since some diagnostic subgroups contained a limited number of samples, especially **Asperger's Disorder**, performing a multi-class classification task could decrease statistical power and increase the possibility of model overfitting. Therefore, all ASD-related diagnoses (**AUTISM**, **PDD-NOS**, and **ASPERGER'S DISORDER**) were combined into one unified ASD class, while **CONTROL** samples were assigned to the healthy control class.

This conversion resulted in a binary classification problem:

- **Control (Label = 0):** Healthy individuals  
- **ASD (Label = 1):** Individuals with autism spectrum-related diagnoses  

This strategy enables a more robust classification model by increasing the number of samples in the disease group and focusing on the primary objective of ASD detection rather than distinguishing between different ASD subtypes.

In [28]:
def convert_label(diagnosis):
    if "CONTROL" in diagnosis:
        return 0
    else:
        return 1


df_gpl6244["Label"] = df_gpl6244["Diagnosis"].apply(convert_label)

df_gpl6244.head()

        Sample            Diagnosis Gender  Age Platform  Label
99   GSM650655  ASPERGER'S DISORDER   male  156  GPL6244      1
100  GSM650656               AUTISM   male  168  GPL6244      1
101  GSM650657              CONTROL   male  228  GPL6244      0
102  GSM650658               AUTISM   male   60  GPL6244      1
103  GSM650659               AUTISM   male   36  GPL6244      1

In [29]:
df_gpl6244["Label"].value_counts()

Label
1    104
0     82
Name: count, dtype: int64

In [31]:
df_gpl6244["Diagnosis"].value_counts()

Diagnosis
CONTROL                82
PDD-NOS                48
AUTISM                 41
ASPERGER'S DISORDER    15
Name: count, dtype: int64

### **Gender Distribution Analysis**

The gender distribution of the selected GPL6244 dataset was examined to evaluate the demographic composition of the samples. The dataset contains **128 male samples** and **58 female samples**.

The distribution across diagnostic groups shows that the control group (**Label = 0**) includes **48 males** and **34 females**, while the ASD group (**Label = 1**) contains **80 males** and **24 females**. This analysis highlights the gender imbalance commonly observed in ASD datasets, where males are more frequently represented than females.

In [27]:
print(df_gpl6244['Gender'].value_counts())

Gender
male      128
female     58
Name: count, dtype: int64

In [30]:
print(df_gpl6244.groupby(['Label', 'Gender']).size())

Label  Gender
0      female    34
       male      48
1      female    24
       male      80
dtype: int64

### **Initial Statistical Description**

The dataset contains 186 samples with complete metadata and no missing values.  
The samples were obtained from the GPL6244 platform. The dataset includes 128 male and 58 female participants.  

The age of participants ranged from 24 to 264 months, with a mean age of 96.8 months.  
The median age was 84 months, indicating a wide age distribution among samples.

All samples were generated using the same microarray platform, ensuring consistency across the dataset.

In [59]:
df_gpl6244.isnull().sum()

Sample       0
Diagnosis    0
Gender       0
Age          0
Platform     0
dtype: int64

In [1]:
df_gpl6244.describe(include="all")

NameError: name 'df_gpl6244' is not defined

Data Exploration

 - Load GEO Dataset ✅

 - Inspect Dataset Structure ✅

 - Extract Sample Metadata ✅

 - Check Platforms ✅

 - Select GPL6244 Platform ✅

 - Convert Diagnosis to Binary Labels ✅

 - Analyze Diagnosis Distribution ✅

 - Analyze Gender Distribution ✅

 - Missing Value Analysis ✅

 - Initial Statistical Description ✅